/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module au_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input usb_rx,
    output reg usb_tx,
    output reg [23:0] io_led,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    input [4:0] io_button,
    input [23:0] io_dip
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  wire [8-1:0] M_init_led;
  wire [1-1:0] M_init_usb_tx;
  wire [24-1:0] M_init_io_led;
  wire [8-1:0] M_init_io_seg;
  wire [4-1:0] M_init_io_sel;
  reg [1-1:0] M_init_usb_rx;
  reg [5-1:0] M_init_io_button;
  reg [24-1:0] M_init_io_dip;
  initialise_2 init (
    .clk(clk),
    .rst(rst),
    .usb_rx(M_init_usb_rx),
    .io_button(M_init_io_button),
    .io_dip(M_init_io_dip),
    .led(M_init_led),
    .usb_tx(M_init_usb_tx),
    .io_led(M_init_io_led),
    .io_seg(M_init_io_seg),
    .io_sel(M_init_io_sel)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    M_init_usb_rx = usb_rx;
    M_init_io_button = io_button;
    M_init_io_dip = io_dip;
    led = M_init_led;
    usb_tx = M_init_usb_tx;
    io_led = M_init_io_led;
    io_seg = M_init_io_seg;
    io_sel = M_init_io_sel;
  end
endmodule
