/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module compareTester_11 (
    input clk,
    input rst,
    input start,
    input lsb,
    output reg [1:0] status
  );
  
  
  
  wire [1-1:0] M_slowclock_value;
  counter_25 slowclock (
    .clk(clk),
    .rst(rst),
    .value(M_slowclock_value)
  );
  
  reg [4:0] M_testCaseNum_d, M_testCaseNum_q = 1'h0;
  
  
  localparam IDLE_state = 2'd0;
  localparam TEST_state = 2'd1;
  localparam PASS_state = 2'd2;
  localparam FAIL_state = 2'd3;
  
  reg [1:0] M_state_d, M_state_q = IDLE_state;
  
  wire [16-1:0] M_alu_out;
  wire [1-1:0] M_alu_z;
  wire [1-1:0] M_alu_v;
  wire [1-1:0] M_alu_n;
  reg [16-1:0] M_alu_a;
  reg [16-1:0] M_alu_b;
  reg [6-1:0] M_alu_alufn;
  reg [1-1:0] M_alu_lsb;
  alu_9 alu (
    .clk(M_slowclock_value),
    .a(M_alu_a),
    .b(M_alu_b),
    .alufn(M_alu_alufn),
    .lsb(M_alu_lsb),
    .out(M_alu_out),
    .z(M_alu_z),
    .v(M_alu_v),
    .n(M_alu_n)
  );
  
  always @* begin
    M_state_d = M_state_q;
    M_testCaseNum_d = M_testCaseNum_q;
    
    M_alu_alufn = 6'h00;
    M_alu_lsb = lsb;
    M_alu_a = 1'h0;
    M_alu_b = 1'h0;
    status = 1'h0;
    if (start == 1'h0) begin
      M_state_d = IDLE_state;
    end
    
    case (M_state_q)
      IDLE_state: begin
        status = 1'h0;
        if (start == 1'h1) begin
          M_state_d = TEST_state;
          M_testCaseNum_d = 1'h0;
        end
      end
      TEST_state: begin
        
        case (M_testCaseNum_q)
          5'h00: begin
            M_alu_a = 16'h0000;
            M_alu_b = 16'h0000;
            M_alu_alufn = 6'h33;
            if (M_alu_out[0+0-:1] != 1'h1) begin
              M_state_d = FAIL_state;
            end
          end
          5'h03: begin
            M_alu_a = 16'h0005;
            M_alu_b = 16'h000b;
            M_alu_alufn = 6'h33;
            if (M_alu_out[0+0-:1] != 1'h0) begin
              M_state_d = FAIL_state;
            end
          end
          5'h04: begin
            M_alu_a = 16'hffff;
            M_alu_b = 16'h0002;
            M_alu_alufn = 6'h33;
            if (M_alu_out[0+0-:1] != 1'h0) begin
              M_state_d = FAIL_state;
            end
          end
          5'h08: begin
            M_alu_a = 16'h0000;
            M_alu_b = 16'h0000;
            M_alu_alufn = 6'h35;
            if (M_alu_out[0+0-:1] != 1'h0) begin
              M_state_d = FAIL_state;
            end
          end
          5'h0b: begin
            M_alu_a = 16'h0005;
            M_alu_b = 16'h000b;
            M_alu_alufn = 6'h35;
            if (M_alu_out[0+0-:1] != 1'h1) begin
              M_state_d = FAIL_state;
            end
          end
          5'h0d: begin
            M_alu_a = 16'h7000;
            M_alu_b = 16'h6fff;
            M_alu_alufn = 6'h35;
            if (M_alu_out[0+0-:1] != 1'h1) begin
              M_state_d = FAIL_state;
            end
          end
          5'h10: begin
            M_alu_a = 16'h0000;
            M_alu_b = 16'h0000;
            M_alu_alufn = 6'h37;
            if (M_alu_out[0+0-:1] != 1'h1) begin
              M_state_d = FAIL_state;
            end
          end
          5'h13: begin
            M_alu_a = 16'h0005;
            M_alu_b = 16'h000b;
            M_alu_alufn = 6'h37;
            if (M_alu_out[0+0-:1] != 1'h1) begin
              M_state_d = FAIL_state;
            end
          end
          5'h16: begin
            M_alu_a = 16'hfffd;
            M_alu_b = 16'hffff;
            M_alu_alufn = 6'h37;
            if (M_alu_out[0+0-:1] != 1'h1) begin
              M_state_d = FAIL_state;
            end
          end
          5'h18: begin
            M_state_d = PASS_state;
          end
        endcase
      end
      PASS_state: begin
        status = 1'h1;
      end
      FAIL_state: begin
        status = 2'h2;
      end
    endcase
    M_testCaseNum_d = M_testCaseNum_q + 1'h1;
  end
  
  always @(posedge M_slowclock_value) begin
    if (rst == 1'b1) begin
      M_state_q <= 1'h0;
    end else begin
      M_state_q <= M_state_d;
    end
  end
  
  
  always @(posedge M_slowclock_value) begin
    if (rst == 1'b1) begin
      M_testCaseNum_q <= 1'h0;
    end else begin
      M_testCaseNum_q <= M_testCaseNum_d;
    end
  end
  
endmodule
